// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('bliblitest1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('bliblitest1', async function() {
    await driver.get("https://www.blibli.com/")
    await driver.manage().window().setRect({ width: 1062, height: 672 })
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.name("search")).sendKeys("iphone 13")
    await driver.findElement(By.css(".searchbox__search > img")).click()
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.css(".searchbox__search")).click()
    await driver.findElement(By.css(".searchbox__action > img")).click()
    await driver.findElement(By.css(".title")).click()
    await driver.findElement(By.css(".skeleton-container__left__main-filter__filters:nth-child(1) > .filter-content:nth-child(4)")).click()
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.css(".active > div")).click()
    {
      const element = await driver.findElement(By.css(".searchbox__search"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".searchbox__search")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("#seller > .drop-down-filter-label")).click()
    await driver.findElement(By.css("div:nth-child(2) > .drop-down-container-row > .drop-down-container-row-name")).click()
    await driver.findElement(By.css(".drop-down-container-buttons-apply")).click()
    assert(await driver.getTitle() == "Online Mall Blibli.com, Sensasi Belanja Online Shop ala Mall")
    {
      const element = await driver.findElement(By.css(".cart__amt"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
